# %%
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from common.math_utils import gaussian_function, lorentzian_function
from common.bose_statistics import boltzmann_factor
from common.honeycomb_lattice import bzmesh, bz_integration_honeycomb
from CrI3.CrI3_raman_scattering import get_RCD, get_energy
from CrI3.CrI3_curvature import get_FM_berry_curvature
from common.model_parameters import CrI3
import scienceplots

# %%  Load pre-computed chi arrays (generated by running this script once)
_DIR = os.path.dirname(os.path.abspath(__file__))
data = np.load(os.path.join(_DIR, 'chi_FM_computed.npz'))
chi_FM_lower_T = data['chi_FM_lower_T']
chi_FM_upper_T = data['chi_FM_upper_T']
chi_FM_lower_D = data['chi_FM_lower_D']
chi_FM_upper_D = data['chi_FM_upper_D']
temperatures   = data['temperatures']
D_array        = data['D_array']
w              = data['w']


def partition_function(energy_array, T=0, mu=0):
    """
    Grand-canonical partition function for bosonic magnons on the BZ.

    Z = exp( integral d^2k/(2pi)^2  ln(1 / (1 - exp(-E_k / k_B T))) )

    Parameters
    ----------
    energy_array : ndarray  magnon energies on the BZ k-mesh (meV)
    T            : float    temperature in K
    mu           : float    chemical potential in meV (default 0)
    """
    return np.exp(
        bz_integration_honeycomb(
            np.log(1 / (1 - boltzmann_factor(energy_array, T=T, mu=mu)))
        ) / (2 * np.pi)**2
    )


# %%  CrI3 parameters and frequency grid
J1, J2, J3, D, Az, S = CrI3['J1'], CrI3['J2'], CrI3['J3'], CrI3['D'], CrI3['Az'], CrI3['S']

w      = np.linspace(0, 20, 300)
len_w  = len(w)
width  = w[1] - w[0]

# %%  Compute chi varying DMI strength D at T = 35 K
D_array = np.linspace(-0.31, 0.31, 101)
len_D   = len(D_array)

chi_FM_lower_D = np.zeros((len_D, len_w))
chi_FM_upper_D = np.zeros((len_D, len_w))

for j in range(len_D):
    RCD_array    = get_RCD(J1=J1, J2=J2, J3=J3, D=D_array[j], Az=Az, S=S)
    energy_array = get_energy(J1=J1, J2=J2, J3=J3, D=D_array[j], Az=Az, S=S)
    partition_arr = (partition_function(energy_array[0], T=35)
                     * partition_function(energy_array[1], T=35))
    for i in range(len_w):
        weight = boltzmann_factor(energy_array[1], T=35) * RCD_array
        kernel = gaussian_function(w[i], x0=np.abs(energy_array[1] - energy_array[0]),
                                   width=width)
        chi_FM_lower_D[j, i] = bz_integration_honeycomb(weight * kernel) / partition_arr
        chi_FM_upper_D[j, i] = chi_FM_lower_D[j, i]   # symmetric by construction

# %%  Compute RCD and energy arrays at nominal D
RCD_array    = get_RCD(**CrI3)
berry_array  = get_FM_berry_curvature(**CrI3)
energy_array = get_energy(**CrI3)

# %%  Compute chi varying temperature T
temperatures  = np.linspace(0, 48, 49)
len_T         = len(temperatures)
partition_array = np.array([
    partition_function(energy_array[0], T=T) * partition_function(energy_array[1], T=T)
    for T in temperatures
])

chi_FM_lower_T = np.zeros((len_T, len_w))
chi_FM_upper_T = np.zeros((len_T, len_w))

for j in range(len_T):
    for i in range(len_w):
        weight = boltzmann_factor(energy_array[1], T=temperatures[j]) * RCD_array
        kernel = gaussian_function(w[i], x0=np.abs(energy_array[1] - energy_array[0]),
                                   width=width)
        chi_FM_lower_T[j, i] = bz_integration_honeycomb(weight * kernel) / partition_array[j]
        chi_FM_upper_T[j, i] = chi_FM_lower_T[j, i]

# %%  Save computed chi arrays
np.savez(os.path.join(_DIR, 'chi_FM_computed.npz'),
         chi_FM_lower_T=chi_FM_lower_T,
         chi_FM_upper_T=chi_FM_upper_T,
         chi_FM_lower_D=chi_FM_lower_D,
         chi_FM_upper_D=chi_FM_upper_D,
         temperatures=temperatures,
         D_array=D_array,
         w=w)

# %%  Berry-curvature-weighted DOS (zero temperature)
dos_weighted_FM = np.zeros(len_w)
for i in range(len_w):
    dos_weighted_FM[i] = bz_integration_honeycomb(
        berry_array[1] * lorentzian_function(
            w[i], x0=np.abs(energy_array[1] - energy_array[0]), width=width
        )
    )

# %%  Diagnostics
print('Max energy:', np.max(energy_array[1]))
print('Partition function (last T):', partition_array[-1])

# %%  Colour palettes
colors_temperature = ['#1a1a1a', '#192225', '#143349', '#245074', '#2f6fa4',
                      '#3989d6', '#76a1ff', '#aaceff', '#e1f0ff']
colors_D = ['#800000', '#b34747', '#cc8080', '#e6b3b3', '#ffcccc',
            '#cce6ff', '#99ccff', '#66b3ff', '#3385ff', '#0066ff', '#0047b3']

# %%  Plot chi(omega, T) — one line per temperature
with plt.style.context(['science', 'ieee']):
    fig, ax = plt.subplots(figsize=(4, 3))

    norm = mpl.colors.Normalize(vmin=temperatures.min(), vmax=temperatures.max())
    cmap = plt.get_cmap('Blues')

    for i, T in enumerate(temperatures):
        ax.plot(w, chi_FM_lower_T[i], color=cmap(norm(T)),
                linewidth=1, alpha=0.9, ls='-')

    sm = mpl.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    clb = fig.colorbar(sm, ax=ax, shrink=0.9)
    clb.ax.set_title(r"$T$", loc='left', fontsize=22)
    clb.ax.tick_params(labelsize=20)
    clb.set_label(r'$(K)$', fontsize=20)

    ax.tick_params(axis='both', labelsize=20)
    ax.set_xlabel(r'$\hslash\omega\ (\mathrm{meV})$', fontsize=22)
    ax.set_ylabel(r'$\chi(\omega, T)$', fontsize=22)
    plt.show()
    fig.savefig('figures/thermal_RCD/CrI3_TRCD_vary_T_more.png', dpi=300, bbox_inches='tight')

# %%  Plot chi(omega, T) — 2-D colour mesh
with plt.style.context(['science', 'ieee']):
    fig, axes = plt.subplots(figsize=(4, 3))
    x, y = np.meshgrid(w, D_array)

    pc  = axes.pcolormesh(x, y, chi_FM_lower_D)
    clb = fig.colorbar(pc, ax=axes, shrink=0.9)
    clb.ax.set_title(r"$\chi$", loc='left', fontsize=16, pad=5)
    clb.ax.tick_params(labelsize=16)

    axes.set_axis_on()
    axes.grid(False)
    axes.set_xlabel(r'$\hslash\omega\ (\mathrm{meV})$', fontsize=18)
    axes.set_ylabel(r'$D\ (\mathrm{meV})$', fontsize=18)
    plt.show()

# %%  Plot chi(omega, D) — one line per D value
with plt.style.context(['science', 'ieee']):
    fig, ax = plt.subplots(figsize=(4, 3))

    norm = mpl.colors.Normalize(vmin=D_array.min(), vmax=D_array.max())
    cmap = plt.get_cmap('RdBu')

    for i, d_val in enumerate(D_array):
        ax.plot(w, chi_FM_lower_D[i], color=cmap(norm(d_val)),
                linewidth=1, alpha=0.9, ls='-')

    sm = mpl.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    clb = fig.colorbar(sm, ax=ax, shrink=0.9)
    clb.ax.set_title(r"$D$", loc='left', fontsize=22)
    clb.ax.tick_params(labelsize=20)
    clb.set_label(r'$(\mathrm{meV})$', fontsize=20)

    ax.tick_params(axis='both', labelsize=20)
    ax.set_xlabel(r'$\hslash\omega\ (\mathrm{meV})$', fontsize=22)
    ax.set_ylabel(r'$\chi(\omega, D)$', fontsize=22)
    plt.show()
    fig.savefig('figures/thermal_RCD/CrI3_TRCD_vary_D_more.png', dpi=300, bbox_inches='tight')
